alfa-laboratory/alfa-ui-primitives

- colors.json
> feat(colors): add warning color

- icons/ui/icon_select-tick_l_black.svg
- icons/ui/icon_select-tick_l_white.svg
- icons/ui/icon_select-tick_m_black.svg
- icons/ui/icon_select-tick_m_white.svg
- icons/ui/icon_select-tick_s_black.svg
- icons/ui/icon_select-tick_s_white.svg
- icons/ui/icon_select-tick_xl_black.svg
- icons/ui/icon_select-tick_xl_white.svg
> feat(icons): remove ui select tick

- icons/action/icon_lock_m_color.svg
- icons/action/icon_lock_xxl_color.svg
add
icon_lock_m_color
icon_lock_xxl_color
> fix(icons): add color lock icons

- icons/action/icon_lock_m_color.svg
- icons/action/icon_lock_xxl_color.svg
- icons/art/art_chart_xs_black.svg
- icons/art/art_chart_xs_color.svg
add
art_chart_xs_color
art_chart_xs_black
> fix(icons): add chart icons

- icons/action/icon_lock_m_black.svg
- icons/action/icon_lock_m_color.svg
- icons/action/icon_lock_m_white.svg
- icons/action/icon_lock_xxl_color.svg
- icons/action/icon_unlock_m_black.svg
- icons/action/icon_unlock_m_white.svg
- icons/art/art_chart_xs_black.svg
- icons/art/art_chart_xs_color.svg
- icons/banking/icon_card-accounts-list_m_black.svg
- icons/banking/icon_card-accounts-list_m_white.svg
add and fix lock_m icons
fix card-accounts icons
> icon(fix): add and fix icons

- icons/banking/icon_transfer-in_l_black.svg
- icons/banking/icon_transfer-in_l_white.svg
- icons/banking/icon_transfer-in_s_black.svg
- icons/banking/icon_transfer-in_s_white.svg
- icons/banking/icon_transfer-in_xl_black.svg
- icons/banking/icon_transfer-in_xl_white.svg
- icons/banking/icon_transfer-out_l_black.svg
- icons/banking/icon_transfer-out_l_white.svg
- icons/banking/icon_transfer-out_s_black.svg
- icons/banking/icon_transfer-out_s_white.svg
- icons/banking/icon_transfer-out_xl_black.svg
- icons/banking/icon_transfer-out_xl_white.svg
До этого были небольшие неточности с отступами. Поэтому пришлось удалить старый пулреквест. 
Это transfer-in/out, которые я пересохранил, так как они сейчас некорректно отображаются в браузере.
> fix(icon) transfer

- icons/action/icon_lock_s_black.svg
- icons/action/icon_lock_s_white.svg
fix icon_lock_s_black
fix icon_lock_s_white
> fix(icons): fix lock_s icons

- icons/entity/icon_clock_xs_black.svg
- icons/entity/icon_clock_xs_white.svg
- icons/ui/icon_check-chat_xs_black.svg
- icons/ui/icon_check-chat_xs_white.svg
> fix(icons): add check-chat and clock xs icons

- icons/banking/icon_card-activation_m_black.svg
- icons/banking/icon_card-activation_m_white.svg
на андроиде поехали card-activate_m иконки
> fix(icons): fix card-activate_m icons

- icons/entity/icon_calendar_l_black.svg
- icons/entity/icon_calendar_l_white.svg
- icons/entity/icon_calendar_m_black.svg
- icons/entity/icon_calendar_m_white.svg
- icons/entity/icon_calendar_s_black.svg
- icons/entity/icon_calendar_s_white.svg
- icons/entity/icon_calendar_xl_black.svg
- icons/entity/icon_calendar_xl_white.svg
побились иконки календаря
+ размеры везде поехали
поменял все
> fix(icons): fix calendar icons

- icons/action/icon_add-filled_black_m.svg
- icons/action/icon_add-filled_white_m.svg
> additional size for marketplace icon

- icons/brand/icon_logo-alfabank_m_color.svg
> icon_logo-alfabank_m_color

- icons/ui/icon_chevron-right_m_black.svg
- icons/ui/icon_chevron-right_m_white.svg
Новые иконки стрелочек для ячеек.
> Chevron icons

- .gitignore
- utils/publish.sh
[Для генерации primitive-colors.css](https://github.com/alfa-laboratory/arui-feather/pull/775) в arui-feather требуется добавить colors.json в собранную версию пакета
> feat(colors): add colors.json to publish

- .github/workflows/build-react-icons.yml
- .github/workflows/publish.yml
- utils/ci.sh
Добавил экшн автопубликации минорного пакета. Публикация запустится, если с момента последнего релиза встречаются коммиты вида `add \d+ icons`.
До конца пока не смог проверить, так как не хочу выпускать лишний пакет.
> add publish ci

- styles/colors_addons.json
- styles/colors_bluetint.json
- styles/colors_indigo.json
- styles/colors_transparent.json
- updated indigo colors (colors_indigo.json)
- updated addons colors (colors_addons.json)
- new bluetint colors (colors_bluetint.json)
- new transparent colors (colors_transparent.json)
> Updated colors from figma robots 🤖

- icons/ui/icon_check-indeterminate_m.svg
- icons/ui/icon_check-indeterminate_s.svg
add colorless indeterminate icons
> feat(*): add colorless indeterminate icons

- icons/action/glyph_cross_m_white.svg
- package.json
Добавил иконку `glyph_cross_m` в белом цвете
> feat(icons): add glyph_cross_m_white.svg

- styles/colors_indigo.json
- styles/typography_android.json
- styles/typography_ios.json
- styles/typography_web.json
* colors_indigo.json
* text: повышена доступность secondary текстов
* graphic: обновился primary_inverted (белый и индиго) и добавлен secondary_inverted (бывший primary_inverted)
* typography_ios.json и typography_android.json
* обновлена группа Headline (iOS bold → semibold, Android bold → medium)
* добавлена группа Legacy (bold заголовки, от которых в дальнейшем откажемся)
> Updated tokens from figma robots 🤖

- icons/action/icon_logout_l.svg
- icons/action/icon_logout_m.svg
- icons/action/icon_logout_s.svg
- icons/action/icon_logout_xl.svg
- icons/ui/icon_check_l.svg
- icons/ui/icon_check_m.svg
- icons/ui/icon_check_s.svg
- icons/ui/icon_check_xl.svg
- icons/ui/icon_check_xxl.svg
Для перевода на темную тему в проекте потребовались иконки без цвета.
> feat(icons): add logout and check icons without colors

- utils/ci.sh
Выпускаем новую версию, если были какие-то изменения в директории `icons`.
Если какие-то иконки были удалены, выпускаем мажорку
> chore(*): update ci

- styles/gradients.json
> feat(tokens): gradients
